name: Update Caddy, build/publish image

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  check:
    name: Update Caddy version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      should-build: ${{ steps.caddy-update.outputs.should-build }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        id: caddy-update
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/scripts/caddy-update.sh"

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "Dockerfile"
          default_author: user_info
          message: "Update Caddy to ${{ steps.caddy-update.outputs.LATEST_CADDY_VERSION }}"


  build:
    name: Build/publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: check
    if: needs.check.outputs.should-build == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update repository
        run: git pull origin main

      - name: Run script
        id: get-version
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/scripts/get-version.sh"

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.LATEST_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          # platforms: linux/amd64
